### ISSUE TITLE
Download blank times when Python is executed in terminal.

### ISSUE THREAD

**Issue by jge162** [daringcalf/canvas-schedule-helper#3]
Hello @daringcalf when I run the code and capture the session `Cookie` and `Course Id` it is downloading blank times for me on the courses **575 and 539.** 

[CSE539.txt](https://github.com/user-attachments/files/16739660/CSE539.txt)

<img width="1290" alt="Screenshot 2024-08-25 at 2 47 09 AM" src="https://github.com/user-attachments/assets/7ddc14f0-c85b-4fc2-a9c8-1ff7c2744cf5">

**All requirement installed successfully, as seen below:**
<img width="983" alt="Screenshot 2024-08-25 at 2 50 10 AM" src="https://github.com/user-attachments/assets/9dc03a83-538c-4ea4-a747-1619e036534d">

**Comment by daringcalf** [comment]
Looking into it.

**Comment by jge162** [comment]
Spoke to Daring and deleting the cache file resolved my issue. 

<img width="861" alt="Screenshot 2024-08-25 at 8 30 11 PM" src="https://github.com/user-attachments/assets/3d4a33ad-140d-425e-a643-f3430dabf299">
